name: "PR body action"
description: "Update PR body because PR comments are annoying :)"
inputs:
  body:
    description: "body"
    required: true
  GITHUB_TOKEN:
    description: "GITHUB_TOKEN"
    required: true
runs:
  using: "node20"
  main: "index.js"
branding:
  icon: "link"
  color: "blue"
